skip coverage on windows

diff --git a/.github/workflows/run_tests_matlab.yml b/.github/workflows/run_tests_matlab.yml
--- a/.github/workflows/run_tests_matlab.yml
+++ b/.github/workflows/run_tests_matlab.yml
@@ -1,14 +1,15 @@
+---
 name: tests and coverage with matlab
 
 on:
 
   push:
     branches:
-      - master
-      - dev
+    - master
+    - dev
 
   pull_request:
-    branches: ["*"]
+    branches: ['*']
 
 jobs:
 
@@ -24,38 +25,53 @@ jobs:
 
     steps:
 
-      - name: Install MATLAB
-        uses: matlab-actions/setup-matlab@v1.2.4
-        with:
-          release: ${{ matrix.version }}
+    - name: Install MATLAB
+      uses: matlab-actions/setup-matlab@v1.2.4
+      with:
+        release: ${{ matrix.version }}
 
-      - name: Clone spm_2_bids
-        uses: actions/checkout@v3
-        with:
-          submodules: true
-          fetch-depth: 2
+    - name: Clone spm_2_bids
+      uses: actions/checkout@v3
+      with:
+        submodules: true
+        fetch-depth: 2
 
-      - name: Install Moxunit and MOcov
-        run: |
-          git clone https://github.com/MOxUnit/MOxUnit.git --depth 1
-          git clone https://github.com/MOcov/MOcov.git --depth 1
+    - name: Install Moxunit and MOcov
+      run: |
+        git clone https://github.com/MOxUnit/MOxUnit.git --depth 1
+        git clone https://github.com/MOcov/MOcov.git --depth 1
 
-      - name: get bids-matlab and JSONio
-        run: make install_dev
+    - name: get bids-matlab and JSONio
+      run: make install_dev
 
-      - name: Run commands
-        uses: matlab-actions/run-command@v1.1.3
-        with:
-          command: cd(fullfile(getenv('GITHUB_WORKSPACE'), '.github', 'workflows')); run tests_matlab;
+    - name: Run commands
+      uses: matlab-actions/run-command@v1.1.3
+      with:
+        command: cd(fullfile(getenv('GITHUB_WORKSPACE'), '.github', 'workflows')); run tests_matlab;
 
-      - name: Run tests
-        run: |
-          cat test_report.log | grep 0
+    - name: Check logs unix
+      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
+      run: grep -q 0 test_report.log || { echo "Some tests failed. Check the 'Run tests' step to know which ones." >&2; exit 1; }
+    - name: Check logs windows
+      if: matrix.os == 'windows-latest'
+      run: |
+        if (-not (Get-Content test_report.log | Select-String -Pattern "0")) {
+          throw "Some tests failed.  Check the 'Run tests' step to know which ones."
+        }
 
-      - name: Code coverage
-        uses: codecov/codecov-action@v3
-        with:
-          file: coverage.xml # optional
-          flags: unittests # optional
-          name: codecov-umbrella # optional
-          fail_ci_if_error: false # optional (default = false)
+    - name: Code coverage
+      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
+      uses: codecov/codecov-action@v3
+      with:
+        file: coverage.xml
+        flags: ${{ matrix.os }}_matlab-${{ matrix.version }}
+        with_coverage: true
+        cover_xml_file: coverage.xml
+
+    - name: Code coverage
+      uses: codecov/codecov-action@v3
+      with:
+        file: coverage.xml
+        flags: ubuntu-latest_octave
+        name: codecov-umbrella
+        fail_ci_if_error: true
